//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace autotrade.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class InstrumentType : global::System.Configuration.ApplicationSettingsBase {
        
        private static InstrumentType defaultInstance = ((InstrumentType)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InstrumentType())));
        
        public static InstrumentType Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection a {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["a"]));
            }
            set {
                this["a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>2:30</string>\r\n  <string>11:30</string>\r\n  <string>15:00</string>\r\n</Array" +
            "OfString>")]
        public global::System.Collections.Specialized.StringCollection ag {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ag"]));
            }
            set {
                this["ag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection al {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["al"]));
            }
            set {
                this["al"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection au {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["au"]));
            }
            set {
                this["au"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection b {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["b"]));
            }
            set {
                this["b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection bu {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["bu"]));
            }
            set {
                this["bu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection c {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["c"]));
            }
            set {
                this["c"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CF {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CF"]));
            }
            set {
                this["CF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cu {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cu"]));
            }
            set {
                this["cu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FG {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FG"]));
            }
            set {
                this["FG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection fu {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["fu"]));
            }
            set {
                this["fu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection i {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["i"]));
            }
            set {
                this["i"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection IF {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IF"]));
            }
            set {
                this["IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection j {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["j"]));
            }
            set {
                this["j"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection l {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["l"]));
            }
            set {
                this["l"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection m {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["m"]));
            }
            set {
                this["m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ME {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ME"]));
            }
            set {
                this["ME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OI {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OI"]));
            }
            set {
                this["OI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection p {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["p"]));
            }
            set {
                this["p"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection pb {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["pb"]));
            }
            set {
                this["pb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PM {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PM"]));
            }
            set {
                this["PM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection rb {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["rb"]));
            }
            set {
                this["rb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RI {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RI"]));
            }
            set {
                this["RI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ru {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ru"]));
            }
            set {
                this["ru"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SR {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SR"]));
            }
            set {
                this["SR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TA {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TA"]));
            }
            set {
                this["TA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TC {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TC"]));
            }
            set {
                this["TC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection v {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["v"]));
            }
            set {
                this["v"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection WH {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WH"]));
            }
            set {
                this["WH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection wr {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["wr"]));
            }
            set {
                this["wr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection y {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["y"]));
            }
            set {
                this["y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection zn {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["zn"]));
            }
            set {
                this["zn"] = value;
            }
        }
    }
}
