//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace autotrade.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50001693")]
        public string InvestorID {
            get {
                return ((string)(this["InvestorID"]));
            }
            set {
                this["InvestorID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05221058")]
        public string Passwd {
            get {
                return ((string)(this["Passwd"]));
            }
            set {
                this["Passwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("大陆期货一联通线路")]
        public string ServerLine {
            get {
                return ((string)(this["ServerLine"]));
            }
            set {
                this["ServerLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.172.206.73")]
        public string dlqh_dianxinIP1 {
            get {
                return ((string)(this["dlqh_dianxinIP1"]));
            }
            set {
                this["dlqh_dianxinIP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41205")]
        public string dlqh_dianxinPort1 {
            get {
                return ((string)(this["dlqh_dianxinPort1"]));
            }
            set {
                this["dlqh_dianxinPort1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.172.206.78")]
        public string dlqh_dianxinIP2 {
            get {
                return ((string)(this["dlqh_dianxinIP2"]));
            }
            set {
                this["dlqh_dianxinIP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41205")]
        public string dlqh_dianxinPort2 {
            get {
                return ((string)(this["dlqh_dianxinPort2"]));
            }
            set {
                this["dlqh_dianxinPort2"] = value;
            }
        }
    }
}
