//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace autotrade.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50001693")]
        public string InvestorID {
            get {
                return ((string)(this["InvestorID"]));
            }
            set {
                this["InvestorID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05221058")]
        public string Passwd {
            get {
                return ((string)(this["Passwd"]));
            }
            set {
                this["Passwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.172.206.73:41205")]
        public string Broker {
            get {
                return ((string)(this["大陆期货一电信线路Trade1"]));
            }
            set {
                this["大陆期货一电信线路Trade1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.172.206.78:41205")]
        public string 大陆期货一电信线路Trade2 {
            get {
                return ((string)(this["大陆期货一电信线路Trade2"]));
            }
            set {
                this["大陆期货一电信线路Trade2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("大陆期货一联通线路")]
        public string SelectedServerLine {
            get {
                return ((string)(this["SelectedServerLine"]));
            }
            set {
                this["SelectedServerLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8888")]
        public string 大陆期货一电信线路BrokerID {
            get {
                return ((string)(this["大陆期货一电信线路BrokerID"]));
            }
            set {
                this["大陆期货一电信线路BrokerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.172.206.73:32111")]
        public string 大陆期货一电信线路Market1 {
            get {
                return ((string)(this["大陆期货一电信线路Market1"]));
            }
            set {
                this["大陆期货一电信线路Market1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.172.206.78:32111")]
        public string 大陆期货一电信线路Market2 {
            get {
                return ((string)(this["大陆期货一电信线路Market2"]));
            }
            set {
                this["大陆期货一电信线路Market2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.172.206.73:41205")]
        public string Selected大陆期货一电信线路Trade {
            get {
                return ((string)(this["Selected大陆期货一电信线路Trade"]));
            }
            set {
                this["Selected大陆期货一电信线路Trade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.172.206.73:32111")]
        public string Selected大陆期货一电信线路Market {
            get {
                return ((string)(this["Selected大陆期货一电信线路Market"]));
            }
            set {
                this["Selected大陆期货一电信线路Market"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210.51.25.90:41205")]
        public string 大陆期货一联通线路Trade1 {
            get {
                return ((string)(this["大陆期货一联通线路Trade1"]));
            }
            set {
                this["大陆期货一联通线路Trade1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210.51.25.86:41205")]
        public string 大陆期货一联通线路Trade2 {
            get {
                return ((string)(this["大陆期货一联通线路Trade2"]));
            }
            set {
                this["大陆期货一联通线路Trade2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210.51.25.90:32111")]
        public string 大陆期货一联通线路Market1 {
            get {
                return ((string)(this["大陆期货一联通线路Market1"]));
            }
            set {
                this["大陆期货一联通线路Market1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210.51.25.86:32111")]
        public string 大陆期货一联通线路Market2 {
            get {
                return ((string)(this["大陆期货一联通线路Market2"]));
            }
            set {
                this["大陆期货一联通线路Market2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210.51.25.90:41205")]
        public string Selected大陆期货一联通线路Trade {
            get {
                return ((string)(this["Selected大陆期货一联通线路Trade"]));
            }
            set {
                this["Selected大陆期货一联通线路Trade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210.51.25.90:32111")]
        public string Selected大陆期货一联通线路Market {
            get {
                return ((string)(this["Selected大陆期货一联通线路Market"]));
            }
            set {
                this["Selected大陆期货一联通线路Market"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8888")]
        public string 大陆期货一联通线路BrokerID {
            get {
                return ((string)(this["大陆期货一联通线路BrokerID"]));
            }
            set {
                this["大陆期货一联通线路BrokerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1061")]
        public string 安信期货一模拟线路BrokerID {
            get {
                return ((string)(this["安信期货一模拟线路BrokerID"]));
            }
            set {
                this["安信期货一模拟线路BrokerID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("219.143.242.155:21205")]
        public string 安信期货一模拟线路Trade1 {
            get {
                return ((string)(this["安信期货一模拟线路Trade1"]));
            }
            set {
                this["安信期货一模拟线路Trade1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("219.143.242.155:21213")]
        public string 安信期货一模拟线路Market1 {
            get {
                return ((string)(this["安信期货一模拟线路Market1"]));
            }
            set {
                this["安信期货一模拟线路Market1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("219.143.242.155:21205")]
        public string Selected安信期货一模拟线路Trade {
            get {
                return ((string)(this["Selected安信期货一模拟线路Trade"]));
            }
            set {
                this["Selected安信期货一模拟线路Trade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("219.143.242.155:21213")]
        public string Selected安信期货一模拟线路Market {
            get {
                return ((string)(this["Selected安信期货一模拟线路Market"]));
            }
            set {
                this["Selected安信期货一模拟线路Market"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>dlqh-telecom</string>
  <string>大陆期货一电信线路</string>
  <string>dlqh-unicom</string>
  <string>大陆期货一联通线路</string>
  <string>dlqh-analog</string>
  <string>大陆期货一模拟线路</string>
  <string>custom</string>
  <string>自定义</string>
  <string>anxinqh-analog</string>
  <string>安信期货一模拟线路</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerLines {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerLines"]));
            }
            set {
                this["ServerLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>买</string>\r\n  <string>卖</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Direction {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Direction"]));
            }
            set {
                this["Direction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>IF1407</string>
  <string>ZN1409</string>
  <string>ZN1410</string>
  <string>RU1409</string>
  <string>RB1501</string>
  <string>CU1409</string>
  <string>AU1412</string>
  <string>AL1409</string>
  <string>AG1412</string>
  <string>Y1501</string>
  <string>PP1409</string>
  <string>P1501</string>
  <string>M1501</string>
  <string>L1409</string>
  <string>JM1409</string>
  <string>JD1409</string>
  <string>J1409</string>
  <string>I1409</string>
  <string>FB1409</string>
  <string>C1501</string>
  <string>BB1409</string>
  <string>A1501</string>
  <string>TC1409</string>
  <string>TA1409</string>
  <string>SR1501</string>
  <string>RM1409</string>
  <string>OI1501</string>
  <string>ME1409</string>
  <string>FG1501</string>
  <string>CF1501</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection INID {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["INID"]));
            }
            set {
                this["INID"] = value;
            }
        }
    }
}
